In [3]:
%run CommonCodeForExperiments.ipynb

In [4]:
from aitia_explorer.algorithms import notears

In [35]:
data = pd.read_csv("https://raw.githubusercontent.com/AMLab-Amsterdam/CEVAE/master/datasets/IHDP/csv/ihdp_npci_1.csv", header = None)
col =  ["treatment", "y_factual", "y_cfactual", "mu0", "mu1" ,]
for i in range(1,26):
    col.append("x"+str(i))
data.columns = col
data = data.astype({"treatment":'bool'}, copy=False)
data.head()

,treatment,y_factual,y_cfactual,mu0,mu1,x1,x2,x3,x4,x5,...,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25
0,True,5.599916,4.318780,3.268256,6.854457,-0.528603,-0.343455,1.128554,0.161703,-0.316603,...,1,1,1,1,0,0,0,0,0,0
1,False,6.875856,7.856495,6.636059,7.562718,-1.736945,-1.802002,0.383828,2.244320,-0.629189,...,1,1,1,1,0,0,0,0,0,0
2,False,2.996273,6.633952,1.570536,6.121617,-0.807451,-0.202946,-0.360898,-0.879606,0.808706,...,1,0,1,1,0,0,0,0,0,0
3,False,1.366206,5.697239,1.244738,5.889125,0.390083,0.596582,-1.850350,-0.879606,-0.004017,...,1,0,1,1,0,0,0,0,0,0
4,False,1.963538,6.202582,1.685048,6.191994,-1.045229,-0.602710,0.011465,0.161703,0.683672,...,1,1,1,1,0,0,0,0,0,0

In [36]:
data['treatment'] = (data['treatment'] == True).astype(int)
data['treatment'] = (data['treatment'] == False).astype(int)
data.head()

,treatment,y_factual,y_cfactual,mu0,mu1,x1,x2,x3,x4,x5,...,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25
0,0,5.599916,4.318780,3.268256,6.854457,-0.528603,-0.343455,1.128554,0.161703,-0.316603,...,1,1,1,1,0,0,0,0,0,0
1,1,6.875856,7.856495,6.636059,7.562718,-1.736945,-1.802002,0.383828,2.244320,-0.629189,...,1,1,1,1,0,0,0,0,0,0
2,1,2.996273,6.633952,1.570536,6.121617,-0.807451,-0.202946,-0.360898,-0.879606,0.808706,...,1,0,1,1,0,0,0,0,0,0
3,1,1.366206,5.697239,1.244738,5.889125,0.390083,0.596582,-1.850350,-0.879606,-0.004017,...,1,0,1,1,0,0,0,0,0,0
4,1,1.963538,6.202582,1.685048,6.191994,-1.045229,-0.602710,0.011465,0.161703,0.683672,...,1,1,1,1,0,0,0,0,0,0

In [43]:
data

,treatment,y_factual,y_cfactual,mu1,x2,x3,x4,x5,x6,x7,...,x14,x15,x17,x18,x19,x21,x22,x23,x24,x25
0,0,5.599916,4.318780,6.854457,-0.343455,1.128554,0.161703,-0.316603,1.295216,1,...,1,0,1,1,1,0,0,0,0,0
1,1,6.875856,7.856495,7.562718,-1.802002,0.383828,2.244320,-0.629189,1.295216,0,...,1,1,1,1,1,0,0,0,0,0
2,1,2.996273,6.633952,6.121617,-0.202946,-0.360898,-0.879606,0.808706,-0.526556,0,...,2,0,0,1,1,0,0,0,0,0
3,1,1.366206,5.697239,5.889125,0.596582,-1.850350,-0.879606,-0.004017,-0.857787,0,...,2,0,0,1,1,0,0,0,0,0
4,1,1.963538,6.202582,6.191994,-0.602710,0.011465,0.161703,0.683672,-0.360940,1,...,1,0,1,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,1,4.091946,6.061976,7.053195,-0.202946,-0.360898,0.161703,-0.316603,1.792063,0,...,1,0,0,1,0,0,0,0,0,0
743,0,5.501677,4.237157,7.084080,-0.202946,-0.733261,-0.879606,0.808706,1.129600,0,...,2,1,1,1,0,0,0,0,0,0
744,1,1.842583,4.949537,6.523225,0.196818,-1.477987,0.161703,0.746189,0.467138,0,...,1,0,1,1,0,0,0,0,0,0
745,1,3.076368,7.554212,6.419095,-0.202946,-1.477987,-0.879606,1.621430,0.467138,1,...,2,0,1,1,0,0,0,0,0,0
746,1,2.928105,5.311445,6.686602,0.596582,-0.360898,-0.879606,0.496120,0.135907,0,...,2,1,1,1,0,0,0,0,0,0

In [37]:
output_dict1 = notears.notears_standard(
                          data, 
                          notears.loss.least_squares_loss, 
                          notears.loss.least_squares_loss_grad, 
                          e=1e-8, 
                          verbose=False)

In [41]:
print('Acyclicity loss: {}'.format(output_dict1['h']))
print('Least squares loss: {}'.format(output_dict1['loss']))

Acyclicity loss: 4.7596167007668555e-09
Least squares loss: 4.447096518949866

In [8]:
# how to draw the graph
G = nx.DiGraph(output_dict['W'])
nx.draw(G)

In [32]:
def get_clustered_dataframe(incoming_df, column_list, sample_size):
    gmm = mixture.BayesianGaussianMixture(n_components=2, 
                                          covariance_type="full", 
                                          n_init=100, 
                                          random_state=42).fit(incoming_df)
    clustered_data = gmm.sample(sample_size)
    clustered_df = pd.DataFrame(clustered_data[0], columns=column_list)
    return clustered_df

In [39]:
data = data.drop(['mu0', 'x1', 'x16', 'x20'], axis=1)

In [40]:
output_dict2 = notears.notears_standard(
                          data, 
                          notears.loss.least_squares_loss, 
                          notears.loss.least_squares_loss_grad, 
                          e=1e-8, 
                          verbose=False)

In [42]:
print('Acyclicity loss: {}'.format(output_dict2['h']))
print('Least squares loss: {}'.format(output_dict2['loss']))

Acyclicity loss: 4.969120226405721e-09
Least squares loss: 4.530257473260698

In [44]:
clustered_df = get_clustered_dataframe(data, list(data), 750)

In [46]:
output_dict3 = notears.notears_standard(
                          clustered_df, 
                          notears.loss.least_squares_loss, 
                          notears.loss.least_squares_loss_grad, 
                          e=1e-8, 
                          verbose=False)
print('Acyclicity loss: {}'.format(output_dict3['h']))
print('Least squares loss: {}'.format(output_dict3['loss']))

Acyclicity loss: 4.091731398148113e-09
Least squares loss: 4.189328934978287

In [50]:
acyclic_1 = notears.utils.threshold_output(output_dict1['W'])
acyclic_2 = notears.utils.threshold_output(output_dict2['W'])
acyclic_3 = notears.utils.threshold_output(output_dict3['W'])

In [51]:
cs = notears.utils.compare_graphs_undirected(acyclic_2, acyclic_3)
print('True positives: {}\nFalse positives: {}\nTrue negatives: {}\nFalse negatives: {}'\
      .format(cs[0], cs[1], cs[2], cs[3]))

True positives: 320
False positives: 3
True negatives: 351
False negatives: 2